# Generated by Django 3.2.7 on 2021-09-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField(unique=True)),
                ('conversation_created_at', models.DateTimeField()),
                ('conversation_closed_at', models.DateTimeField()),
                ('intercom_user_id', models.CharField(max_length=50, unique=True)),
                ('intercom_user_name', models.CharField(max_length=50)),
                ('intercom_user_email', models.EmailField(max_length=254)),
                ('teammate_id', models.CharField(max_length=50, unique=True)),
                ('teammate_name', models.CharField(max_length=50)),
                ('teammate_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
