# Generated by Django 3.2.7 on 2021-09-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210902_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_closed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_created_at',
            field=models.DateTimeField(),
        ),
    ]
