# Generated by Django 3.2.7 on 2021-09-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_conversation_intercom_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.IntegerField(),
        ),
    ]
