# Generated by Django 3.2.7 on 2021-09-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
