# Generated by Django 3.2.7 on 2021-09-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210902_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.IntegerField(unique=True),
        ),
    ]
