# Generated by Django 3.2.7 on 2021-09-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_conversation_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_impacted_sale',
            field=models.BooleanField(default=False),
        ),
    ]
