# Generated by Django 3.2.7 on 2021-09-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_conversation_conversation_impacted_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='teammate_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
