# Generated by Django 3.2.7 on 2021-09-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_conversation_teammate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='intercom_user_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
